---   
# tasks to be performed to install java
- name: Install java 8 preresequesits
  apt: name=python-software-properties

- name: Add Java 8 repository
  apt_repository: repo='ppa:webupd8team/java'

- name: Agree to Oracle license
  debconf: name=oracle-java8-installer question=shared/accepted-oracle-license-v1-1 vtype=select value=true

- name: Install java 8
  apt: name=oracle-java8-installer state=latest update-cache=yes force=yes